package FridayTest;

import java.util.Scanner;

import FridayTest.NegativeNumberException;
import FridayTest.Calculator;

public class DemoException {

	public static void main(String[] args) {
		Scanner s=new Scanner (System.in);
		System.out.println("enter the num1");
		int d=s.nextInt();
		System.out.println("Enter the num2");
		int f=s.nextInt();
	
		try {
		Calculator a = new Calculator(d,f);
		a.Calculator();
	}
		catch(NegativeNumberException e)
		{
			System.out.println(e.showMessage());
		}
		catch(Exception c)
		{
			System.out.println(c);
		}
		
		
	}
}

	}

}
